### PR TITLE
Fix for #35 for the URL encoding of SVGs which breaks IE and Firefox

### PR DESCRIPTION
**Pull request by dkeeghan**
Fix based on @ttaiyo's comment on Issue #35

### CODE REVIEW

**Comment by dkeeghan** [comment]
Hey @jefflembeck, 

Here is the example with the same image using `&#x3D;` (red), `%3D` (green) and `=` (yellow)
http://codepen.io/dkeeghan/pen/qrwozQ

On Chrome 56, macOS 10.12.3
image

On Firefox 52, macOS 10.12.3
image

**Comment by dkeeghan** [comment]
@jefflembeck using the modern.ie IE11 VM:
Windows 8.1, IE11
image

Windows 8.1, Firefox 52.0.2 
image

Windows 8.1, Chrome 57
image

Safari 10.0.3, macOS 10.12.3
image

**Comment by SevInf** [comment]
@jefflembeck can this be merged? We are having the same issue.

**Comment by danez** [comment]
It seems like that `directory-encoder` is already escaping the data-uri correctly, so that in the handlebar-template one could/should use tripple curlies anyway, which also solves the problem.

```css
background-image: url('{{{datauri}}}');
```
http://handlebarsjs.com/#html-escaping

**Comment by zachleat** [comment]
Tested `data:image/svg+xml;charset%3DUS-ASCII,…` urls, worked fine in IE9 too. I’m gonna merge this.

Thank you @dkeeghan!

**Pull request merged**
