### PR TITLE
Expose Handlebars object for extension

### PR DESCRIPTION
**Pull request by art0rz**
This change adds a optional configuration option `handlebarsCallback`. When this option is supplied as a function, the function is called with the handlebars instance as an argument. This enables the user to add custom helpers and other configuration properties to the handlebars instance used by directory-encoder. This change fixes issue #28.

### CODE REVIEW

**Comment by jmdrawneek** [comment]
Nice work. Would love this functionality. Is there anything I can do to help progress it?

**Comment by art0rz** [comment]
No, the feature is complete. If you want to use the module with this new feature, you can use my fork.

**Comment by jefflembeck** [comment]
Sorry for the slow movement on this. Totally missed it. Thank you for the
PR. When I'm at a computer next week, I'll give this a review

**Comment by art0rz** [comment]
Added unit tests for new functionality.

@jmdrawneek yes, that should work. Can you try with a basic helper like the one in the unit test?

**Comment by jmdrawneek** [comment]
@art0rz I tried the simple add helper and it also failed. Although I've just realised this is specifically for the directory encoder module and not the parent module grunticon. I'll have to investigate passing the functions from there.

**Comment by art0rz** [comment]
Hmm. Did you use my fork?

```
npm install github.com/art0rz/directory-encoder
```

**Comment by jmdrawneek** [comment]
I replaced grunticon-lib's dependency of directory-encoder with your fork.

**Comment by jefflembeck** [comment]
I'm happy with this addition, thanks.

**Comment by jefflembeck** [comment]
Shipped in `0.9.0`

**Pull request merged**
